export default {
//Menu List
  menus: {
    permission: 'menu.menus.index',
    activated: true,
    path: '/menus',
    name: 'qmenu.admin.menus',
    page: () => import('@imagina/qmenu/_layouts/admin/menus/index'),
    layout: () => import('src/layouts/master'),
    title: 'qmenu.sidebar.adminMenus',
    icon: 'fas fa-stream',
    authenticated: true,
  },
  menusShow: {
    permission: 'menu.menus.edit',
    activated: true,
    path: '/menus/menu/:id',
    name: 'qmenu.admin.menus.show',
    page: () => import('@imagina/qmenu/_layouts/admin/menus/show'),
    layout: () => import('src/layouts/master'),
    title: 'qmenu.sidebar.adminMenus',
    icon: 'fas fa-stream',
    authenticated: true,
  },
  menuItemsCreate: {
    permission: null,
    activated: true,
    path: '/menus/item/:menuId',
    name: 'qmenu.admin.menu.create',
    page: () => import('@imagina/qmenu/_layouts/admin/menuitems/form'),
    layout: () => import('src/layouts/master'),
    title: 'qmenu.sidebar.adminMenuItems',
    icon: 'fas fa-circle',
    authenticated: true,
  },
  menuItemsUpdate: {
    permission: null,
    activated: true,
    path: '/menus/menu/:menuId/item/:id',
    name: 'qmenu.admin.menu.update',
    page: () => import('@imagina/qmenu/_layouts/admin/menuitems/form'),
    layout: () => import('src/layouts/master'),
    title: 'qmenu.sidebar.adminMenuItems',
    icon: 'fas fa-circle',
    authenticated: true,
  },
}
